import { useState } from "react";
import { verifyOtp } from "../services/api";

function OtpVerification() {

    const username =
        localStorage.getItem(
            "otpUsername"
        );

    const [otp, setOtp] =
        useState("");

    const [message, setMessage] =
        useState("");

    async function handleVerify(e) {

        e.preventDefault();

        const data =
            await verifyOtp(
                username,
                otp
            );

        if (data.token) {

            localStorage.setItem(
                "token",
                data.token
            );

            localStorage.setItem(
                "username",
                username
            );

            localStorage.removeItem(
                "otpUsername"
            );

            window.location.reload();

            return;
        }

        setMessage(data.message);
    }

    return (
        <div className="auth-container">

            <div className="auth-card">

                <h1>MFA Verification</h1>

                <p>
                    OTP was generated by
                    the backend.
                </p>

                <p>
                    Check the Spring Boot
                    console.
                </p>

                <form
                    onSubmit={handleVerify}
                >

                    <input
                        type="text"
                        maxLength="6"
                        placeholder="Enter OTP"
                        value={otp}
                        onChange={
                            e =>
                                setOtp(
                                    e.target.value
                                )
                        }
                    />

                    <button type="submit">
                        Verify OTP
                    </button>

                </form>

                <p>{message}</p>

            </div>

        </div>
    );
}

export default OtpVerification;